services:
  tunnara-server:
    environment:
      TUNNARA_BEHIND_TLS_PROXY: "true"
      TUNNARA_PUBLIC_SCHEME: https
      TUNNARA_PUBLIC_CONTROL_URL: https://control.${TUNNARA_BASE_DOMAIN}
      TUNNARA_PUBLIC_RELAY_URL: ${TUNNARA_PUBLIC_RELAY_URL:-tcp://relay.${TUNNARA_BASE_DOMAIN}:7300}
      TUNNARA_PUBLIC_EDGE_HOST: ${TUNNARA_BASE_DOMAIN}
      TUNNARA_AUTO_DNS: ${TUNNARA_AUTO_DNS:-true}
      TUNNARA_MASTER_KEY_BASE64: ${TUNNARA_MASTER_KEY_BASE64:?Execute ./tunnara.sh init}
      TUNNARA_CLOUDFLARE_EDGE_ADDRESS: ${TUNNARA_CLOUDFLARE_EDGE_ADDRESS:-}
      TUNNARA_CLOUDFLARE_EDGE_HOSTNAME: ${TUNNARA_CLOUDFLARE_EDGE_HOSTNAME:-}
  caddy:
    image: ${TUNNARA_CADDY_IMAGE:-ghcr.io/wkarts/tunnara-caddy-cloudflare:1.1.2}
    pull_policy: ${TUNNARA_PULL_POLICY:-missing}
    restart: unless-stopped
    depends_on:
      tunnara-server:
        condition: service_healthy
      console:
        condition: service_started
    environment:
      TUNNARA_BASE_DOMAIN: ${TUNNARA_BASE_DOMAIN:?Defina TUNNARA_BASE_DOMAIN}
      TUNNARA_ACME_EMAIL: ${TUNNARA_ACME_EMAIL:?Defina TUNNARA_ACME_EMAIL}
      TUNNARA_ACME_CA: ${TUNNARA_ACME_CA:-https://acme-v02.api.letsencrypt.org/directory}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?Defina CLOUDFLARE_API_TOKEN}
    volumes:
      - ./cloudflare/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    networks: [tunnara]

  cloudflared:
    image: cloudflare/cloudflared:latest
    profiles: [cloudflare-tunnel]
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol quic run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - caddy
    networks: [tunnara]

volumes:
  caddy_data:
  caddy_config:
