services:
  control-api:
    build:
      context: ../../../apps/control-api
      dockerfile: Dockerfile
    pull_policy: build

  console:
    build:
      context: ../../../apps/console
      dockerfile: Dockerfile
      args:
        VITE_TUNNARA_API_URL: /control
    pull_policy: build
