{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tunnara.secretName" . }}
  labels: {{- include "tunnara.labels" . | nindent 4 }}
type: Opaque
stringData:
  bootstrap-admin-token: {{ required "Defina --set-string server.bootstrapAdminToken=tnr_admin_... ou server.existingSecret" .Values.server.bootstrapAdminToken | quote }}
  master-key-base64: {{ required "Defina --set-string server.masterKeyBase64=... ou server.existingSecret" .Values.server.masterKeyBase64 | quote }}
  cluster-token: {{ required "Defina --set-string server.clusterToken=tnr_cluster_... ou server.existingSecret" .Values.server.clusterToken | quote }}
{{- end }}
