name: TunnaraMobile
options:
  bundleIdPrefix: br.com.wwsoftwares.tunnara
  deploymentTarget:
    iOS: "16.0"
packages:
  WireGuardKit:
    path: .wireguard-apple
targets:
  WireGuardGoBridgeiOS:
    type: tool
    platform: iOS
    legacy:
      toolPath: /usr/bin/make
      workingDirectory: $(PROJECT_DIR)/.wireguard-apple/Sources/WireGuardKitGo
      passSettings: true
    settings:
      base:
        SDKROOT: iphoneos
  TunnaraMobileSimulator:
    type: application
    platform: iOS
    sources: [TunnaraApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.wwsoftwares.tunnara.mobile.simulator
        PRODUCT_NAME: TunnaraMobile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Tunnara
        INFOPLIST_KEY_CFBundleShortVersionString: 2.0.0
        INFOPLIST_KEY_CFBundleVersion: 200007008
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 200007008
        SWIFT_VERSION: 5.10
        ENABLE_BITCODE: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
  TunnaraMobile:
    type: application
    platform: iOS
    sources: [TunnaraApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.wwsoftwares.tunnara.mobile
        PRODUCT_NAME: TunnaraMobile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Tunnara
        INFOPLIST_KEY_CFBundleShortVersionString: 2.0.0
        INFOPLIST_KEY_CFBundleVersion: 200007008
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 200007008
        CODE_SIGN_ENTITLEMENTS: Config/TunnaraMobile.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: $(TUNNARA_APPLE_TEAM_ID)
        PROVISIONING_PROFILE_SPECIFIER: $(TUNNARA_APP_PROFILE_SPECIFIER)
        SWIFT_VERSION: 5.10
        ENABLE_BITCODE: NO
    dependencies:
      - target: TunnaraPacketTunnel
        embed: true
      - package: WireGuardKit
        product: WireGuardKit
  TunnaraPacketTunnel:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources: [TunnaraPacketTunnel]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.wwsoftwares.tunnara.mobile.packet-tunnel
        PRODUCT_NAME: TunnaraPacketTunnel
        INFOPLIST_FILE: Config/PacketTunnel-Info.plist
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 200007008
        CODE_SIGN_ENTITLEMENTS: Config/TunnaraPacketTunnel.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: $(TUNNARA_APPLE_TEAM_ID)
        PROVISIONING_PROFILE_SPECIFIER: $(TUNNARA_PACKET_PROFILE_SPECIFIER)
        SWIFT_VERSION: 5.10
        ENABLE_BITCODE: NO
    dependencies:
      - target: WireGuardGoBridgeiOS
      - package: WireGuardKit
        product: WireGuardKit
