name: TunnaraMobile
options:
  bundleIdPrefix: br.com.wwsoftwares.tunnara
  deploymentTarget:
    iOS: "16.0"
packages:
  WireGuardKit:
    url: https://git.zx2c4.com/wireguard-apple
    exactVersion: 1.0.16-27
targets:
  TunnaraMobile:
    type: application
    platform: iOS
    sources: [TunnaraApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.wwsoftwares.tunnara.mobile
        PRODUCT_NAME: TunnaraMobile
        INFOPLIST_KEY_CFBundleDisplayName: Tunnara
        INFOPLIST_KEY_CFBundleShortVersionString: 1.1.1
        INFOPLIST_KEY_CFBundleVersion: 10101
        MARKETING_VERSION: 1.1.1
        CURRENT_PROJECT_VERSION: 10101
        CODE_SIGN_ENTITLEMENTS: Config/TunnaraMobile.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: $(TUNNARA_APPLE_TEAM_ID)
        PROVISIONING_PROFILE_SPECIFIER: $(TUNNARA_APP_PROFILE_SPECIFIER)
        SWIFT_VERSION: 5.10
    dependencies:
      - target: TunnaraPacketTunnel
        embed: true
  TunnaraPacketTunnel:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources: [TunnaraPacketTunnel]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.wwsoftwares.tunnara.mobile.packet-tunnel
        PRODUCT_NAME: TunnaraPacketTunnel
        INFOPLIST_FILE: Config/PacketTunnel-Info.plist
        MARKETING_VERSION: 1.1.1
        CURRENT_PROJECT_VERSION: 10101
        CODE_SIGN_ENTITLEMENTS: Config/TunnaraPacketTunnel.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: $(TUNNARA_APPLE_TEAM_ID)
        PROVISIONING_PROFILE_SPECIFIER: $(TUNNARA_PACKET_PROFILE_SPECIFIER)
        SWIFT_VERSION: 5.10
    dependencies:
      - package: WireGuardKit
        product: WireGuardKit
