<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import BasePage from "../../components/base/BasePage.vue"; import BaseSectionCard from "../../components/base/BaseSectionCard.vue"; import BaseDataGrid from "../../components/base/BaseDataGrid.vue"; import ControlAccessPanel from "../../components/ControlAccessPanel.vue";
import { createNetwork, deleteNetwork, listNetworkPeers, listNetworks, type PrivateNetwork } from "../../services/tunnaraApi";
const columns=[{key:"name",label:"Rede"},{key:"cidr",label:"CIDR virtual"},{key:"dns_domain",label:"DNS interno"},{key:"mode",label:"Topologia"},{key:"peerCount",label:"Peers"},{key:"status",label:"Status"}];
const rows=ref<Record<string,unknown>[]>([]); const loading=ref(false); const error=ref(""); const info=ref("");
const form=reactive({name:"Rede Corporativa",cidr:"100.96.0.0/24",dnsDomain:"corp.tunnara",mode:"hub-spoke" as "hub-spoke"|"mesh"});
async function load(){loading.value=true;error.value="";try{const networks=await listNetworks();rows.value=await Promise.all(networks.map(async(n:PrivateNetwork)=>{let peerCount=0;try{peerCount=(await listNetworkPeers(n.id)).data.length;}catch{}return{...n,peerCount};}));}catch(e){error.value=e instanceof Error?e.message:"Falha ao carregar redes.";}finally{loading.value=false;}}
async function submit(){try{await createNetwork({name:form.name,cidr:form.cidr,dnsDomain:form.dnsDomain||undefined,mode:form.mode});info.value="Rede privada criada. Os Agents podem aderir pela API local/CLI.";await load();}catch(e){error.value=e instanceof Error?e.message:"Falha ao criar rede.";}}
async function remove(row:Record<string,unknown>){if(!confirm(`Excluir a rede ${String(row.name)}?`))return;try{await deleteNetwork(String(row.id));await load();}catch(e){error.value=e instanceof Error?e.message:"Falha ao excluir rede.";}}
onMounted(load);
</script>
<template><BasePage title="Redes privadas WireGuard" subtitle="Rede virtual, peers, chaves por dispositivo e topologia hub-spoke ou mesh." eyebrow="Tunnara Platform 1.0" icon="network"><template #actions><button class="primary" @click="load">Atualizar</button></template><ControlAccessPanel @saved="load"/><div v-if="error" class="alert error">{{error}}</div><div v-if="info" class="alert info">{{info}}</div><BaseSectionCard title="Nova rede privada" subtitle="A ativação da interface exige WireGuard instalado e privilégios no dispositivo Agent."><div class="grid two-cols"><div class="field"><label>Nome</label><input v-model="form.name"/></div><div class="field"><label>CIDR IPv4</label><input v-model="form.cidr"/></div><div class="field"><label>Domínio DNS interno</label><input v-model="form.dnsDomain"/></div><div class="field"><label>Topologia</label><select v-model="form.mode"><option value="hub-spoke">Hub-spoke</option><option value="mesh">Mesh</option></select></div></div><div class="actions top-gap-12"><button class="primary" @click="submit">Criar rede</button></div></BaseSectionCard><BaseSectionCard title="Redes cadastradas"><BaseDataGrid :rows="rows" :columns="columns" empty-text="Nenhuma rede privada."><template #actions="{row}"><button class="secondary compact-button" @click="remove(row)">Excluir</button></template></BaseDataGrid></BaseSectionCard></BasePage></template>
